### ISSUE TITLE
Difference between the marching cube algothrim of pytorch3d

### ISSUE THREAD

**Issue by Puzzled-Hui** [tatsy/mcubes_pytorch#12]
Dear authors, 

Thanks for this excellent repo,

I have one small concern, that what is the difference between this repo and the marching cube algorithm in pytorch3d: https://github.com/facebookresearch/pytorch3d/issues/532

**Comment by tatsy** [comment]
I am not prettey sure about "Pytorch3D", but this library provides the simple implementation of the marching cubes algorithm implemented on CUDA and PyTorch.
