### ISSUE TITLE
torch should be a requirement

### ISSUE THREAD

**Issue by truedat101** [tatsy/mcubes_pytorch#15]
One cannot install torchmcubes without torch.  Please add it to the requirements or instructions:

pip install torch

**Comment by AbhinavJangra29** [comment]
did anything work for you?

**Comment by truedat101** [comment]
yes, above worked.  However, your torch configuration needs to match whatever version of CUDA you have installed that needs to also match whatever version of CUDA is supported with this project.

**Comment by da2r-20** [comment]
> yes, above worked. However, your torch configuration needs to match whatever version of CUDA you have installed that needs to also match whatever version of CUDA is supported with this project.

CUDA is now shipped as pypi packages which torch, above a certain version depends on.

**Comment by tatsy** [comment]
Now I have added "torch" as a requirement. If your system already have torch installed, then, I think CUDA-enabled library will be installed 👍
