### ISSUE TITLE
Compatibility with CUDA 11

### ISSUE THREAD

**Issue by balisujohn** [tatsy/mcubes_pytorch#17]
So I have nvcc 11.5 installed on Ubuntu 22.04. And when I install torchmcubes as follows:

````
python3.10 -m venv env
source env/bin/activate
python3 -m pip install git+https://github.com/tatsy/torchmcubes.git
````

I get this error message

````
...
RuntimeError:
The detected CUDA version (11.5) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions.   
...
````

It seems like cuda 12 is hardcoded in this project; would it be possible to add compatibility with cuda 11.x?

**Comment by balisujohn** [comment]
````
python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu115
````
````
python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
````
It still fails with either of these commands called beforehand, making me think the poetry lock is overriding them or something like that.

**Comment by balisujohn** [comment]
This fixes it, looks like it's the change to poetry that breaks compatibility with cuda 11.x

````
python3 -m pip install git+https://github.com/tatsy/torchmcubes.git@3aef8afa5f21b113afc4f4ea148baee850cbd472
````

**Comment by tatsy** [comment]
I do not think this is the problem of this repo. You should use the same version of CUDA on your local computer and that for PyTorch

**Comment by balisujohn** [comment]
Could be on my side, but if anyone else has cuda 11 and gets the same error as me, you can fix it using the command I posted.
