### ISSUE TITLE
Marching Cubes in batches

### ISSUE THREAD

**Issue by pengsongyou** [tatsy/mcubes_pytorch#4]
Hi @tatsy Thanks so much for your amazing implementation of Marching Cubes in PyTorch!

I am wondering if your implementation supports running marching cubes in batches? Let's say we have N = 16 implicit fields, can we output 16 meshes out of it directly? Would be super great if your implementation can support it!

Thanks in advance!

Best,
Songyou

**Comment by aluo-x** [comment]
It does actually work on batched tensors. I have an implementation for a paper currently in submission, I can share the code in a couple of months (assuming the paper is accepted).

The basic idea is that you can wrap the mcubes function inside a data parallel object, using a for loop on each GPU. You will also need to figure out a way to deal with variable numbers of nodes in pytorch `__gather__`.

**Comment by pengsongyou** [comment]
Thanks for the reply! I was trying to implemnt it myself, but realize that each sample in a batch might result in a different number of vertices and faces. How actually are you able to deal with this problem in batching? Do you predefine a large output vertex and face tensor and fill every element in a batch into it?

Thanks again for your reply!

**Comment by aluo-x** [comment]
I just reused some code from a previous graph cnn project. I implemented my own gather function, similar to how pytorch geometric implemented their `forward` for [graph based dataparallel](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/data_parallel.html), see [here specifcially](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/batch.html?highlight=from_data_list#). So you don't need to predefine a giant output tensor. 

This is the [code I based my implementation on](https://github.com/aluo-x/3D_SLN/blob/0a29dbf17e3ca58064e76f9227f536a127c4863b/data/suncg_dataset.py#L295) for a graph based `collate`, the `gather` function is very similar.

edit: typo

**Comment by tatsy** [comment]
@pengsongyou Because this code has already been using CUDA, I think there is no much computational overhead even when you use this program in an ordinary for loop. However, as you mentioned, such a usage will make another problem of different number of vertices and faces for each batched data. So, another workaround, e.g., making a large tensor, or the one suggested by @aluo-x, will be necessary.

Having said so, this is rather out of scope of the purpose of this program, please let me close this issue, while I always welcome your PR to make the batched data available.

Thank you.

**Comment by JIANG-CX** [comment]
> Thanks for the reply! I was trying to implemnt it myself, but realize that each sample in a batch might result in a different number of vertices and faces. How actually are you able to deal with this problem in batching? Do you predefine a large output vertex and face tensor and fill every element in a batch into it?
> 
> Thanks again for your reply!

Hi, I wonder whether have you found a solution since I meet the same problem.
