### ISSUE TITLE
Build fails with `No module named 'torch'` (solution)

### ISSUE THREAD

**Issue by shrubb** [tatsy/mcubes_pytorch#5]
Hi, and thanks for the implementation!

Just wanted to let other users know about a build problem.

My default Python is `python3.7`. The installation fails because `pip` is trying to invoke `python` instead:

```
$ python3.7 -m pip install .

  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /home/shrubb/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpjpnon38i
       cwd: /home/shrubb/Projects/mcubes_pytorch
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/shrubb/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/shrubb/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/shrubb/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-2ine7t9t/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 155, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-2ine7t9t/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-2ine7t9t/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-2ine7t9t/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 2, in <module>
      from torch.utils.cpp_extension import BuildExtension
  ModuleNotFoundError: No module named 'torch'
  ----------------------------------------
```

The solution is to delete (or move or rename) `pyproject.toml`.

**Comment by tatsy** [comment]
Hi @shrubb,

This is a problem of a newer Pip. When `pyproject.toml` exists, the newer Pip builds the scripts differently ([PEP 517](https://www.python.org/dev/peps/pep-0517/)).

To disable this, add a flag `--no-use-pep517` to Pip.

Hope this helps!

**Comment by tatsy** [comment]
To avoid any misunderstanding, I removed `pyproject.toml`.
Now you can simpy install the module by: 
```shell
pip install git+https://github.com/tatsy/torchmcubes.git
```

**Comment by shodanx2** [comment]
Hi there,
Just hit this issue, seems to still be alive.
Trying to install TripoSR on windows 10

![image](https://github.com/tatsy/torchmcubes/assets/10621885/c12db026-1559-4566-b508-529921e0a8d1)

**Comment by tatsy** [comment]
Hi @shodanx2, I do not think this is the problem of this repo. Please consult the owner of TripoSR. If you cannot install this repo directly with pip to your enviroment (i.e., run "pip install git+https://github.com/tatsy/torchmcubes.git" directly), then, please let me know with the errors you received.

**Comment by shodanx2** [comment]
Hi,

Still digging through this. I have a fresh python install, I suspect all people trying out TripoSR will hit the same roadblock here. 
It's an image-to-3d model that just came out yesterday.

I'm not sure I'm still in the TripoSR setup proper, it fails installing the requirements 

Found similar issue

https://github.com/facebookresearch/xformers/issues/740

I tried after a restart, to just install torchmcubes alone, using the command suggested above

`pip install git+https://github.com/tatsy/torchmcubes.git`

![image](https://github.com/tatsy/torchmcubes/assets/10621885/c9832e5f-1bd5-4d7f-92dc-3334fd135a7e)

I tried --no-use-pep517, got 

```
--no-use-pep517 error: It is not possible to use --no-use-pep517
without setuptools and wheel installed.
```

So far I installed python from https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe

then ran 

```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install --upgrade setuptools
pip install -r requirements.txt
```


So there isn't much room for errors...

There in particular

```
_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
```

The other thread says "install wheel

Progress, the error has changed

![image](https://github.com/tatsy/torchmcubes/assets/10621885/ceb9bd75-0838-420c-b70d-f7b718a29d7a)

`"we could not find ninja"`

New error, progress !

![image](https://github.com/tatsy/torchmcubes/assets/10621885/d6e9e85e-ca56-4838-b607-8bf46b8a9bab)

"error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/"

Ok installing https://download.visualstudio.microsoft.com/download/pr/5e7b923b-7d89-4e14-95b8-a84ab168e243/5b539dc7ab1e94494083793fe65c41a6b0fe3b1cdeb38ddd9d04c151c3c2fcf0/vs_BuildTools.exe

Oh I bet that is going to re-activate windows update and wreck my system :(   oh well, yolo, windows re-install after this !

![image](https://github.com/tatsy/torchmcubes/assets/10621885/b2fb9e6a-5bb9-47eb-b813-8fd64752872a)


Installed but still getting the same error.

So I'm hitting post here and restarting the computer.

**Comment by shodanx2** [comment]
Ok, 

Still did not work, had another look at the MS build tools

![image](https://github.com/tatsy/torchmcubes/assets/10621885/f398cdea-1949-4a05-816d-de9f9aba0832)


This is not enough
It needs Visual Studio Community plus the "workload" Desktop C++


![image](https://github.com/tatsy/torchmcubes/assets/10621885/836b10be-b5b3-48df-913c-d09dcb16a0a3)

Now it builds

![image](https://github.com/tatsy/torchmcubes/assets/10621885/378d2e49-5253-4ea9-962d-06bd9048c76c)


TripoSR-main>pip install -r requirements.txt   gets pasts torchmcubes !

![image](https://github.com/tatsy/torchmcubes/assets/10621885/ab4bc9b0-dd22-4775-b276-8c380aec8fd8)

installed rust package manager https://win.rustup.rs/x86_64

and requirements finishes

![image](https://github.com/tatsy/torchmcubes/assets/10621885/995dfa96-b08c-4242-9141-fb7b5d5d0fd3)

total success

![image](https://github.com/tatsy/torchmcubes/assets/10621885/2d2508f6-6cf5-4177-876c-75da223bd325)


So recap, for anyone ending up here from TripoSR

here are your steps for a fresh windows 10 install

```
install python https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe
install MS Visual C++ at https://visualstudio.microsoft.com/visual-cpp-build-tools/
choose Visual Studio community  and Desktop C++ and build tools
Install rust package manager from https://win.rustup.rs/x86_64
download TripoSR https://github.com/VAST-AI-Research/TripoSR/archive/refs/heads/main.zip
uncompress tar -xf TripoSR-main.zip
restart your terminal and maybe reboot here
install torch with   pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
run the following
pip install --upgrade setuptools
pip install wheel
pip install ninja
pip install -r requirements.txt
```


and then magic !

python run.py examples/chair.png --output-dir output/





error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":

**Comment by tatsy** [comment]
From my understanding, maybe the problem is your Python version. As 3.12 is a bit rather new, maybe the correct combination of Python 3.12 and PyTorch, TorchVision, and CUDAToolkit cannot be found.

So, I think downgrading your Python to 3.9 or 3.10 may resolve the problem. Cheers.

**Comment by Cazforshort** [comment]
I have this issue as well on 3.9. Basically everything else the same.
`--> RUN --mount=target=requirements.txt,source=requirements.txt 	pip install --no-cache-dir -r requirements.txt
Collecting git+https://github.com/tatsy/torchmcubes.git (from -r requirements.txt (line 16))
  Cloning https://github.com/tatsy/torchmcubes.git to /tmp/pip-req-build-ia4y_d13
  Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git /tmp/pip-req-build-ia4y_d13
  Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-ia4y_d13/setup.py", line 2, in <module>
          from torch.utils.cpp_extension import BuildExtension
      ModuleNotFoundError: No module named 'torch'
      [end of output]`

**Comment by LEEbugking** [comment]
thx my friend,"install wheel" solved my problem ,too. :)

**Comment by LEEbugking** [comment]
> Ok,
> 
> Still did not work, had another look at the MS build tools
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311176913-f398cdea-1949-4a05-816d-de9f9aba0832.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExNzY5MTMtZjM5OGNkZWEtMTk0OS00YTA1LTgxNmQtZGU5ZjlhYmEwODMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwNWJmOWY1OWY3ZWEyNDc5NzAzOTM4NDNlZTQ3MWI5MjYyMjVhYmFmNmY2Mzg2OGI5YTM4NWI1MDY4MWJhNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bYppu6ghXv_Gy1N_WHKhJhtireS-97jtfRBz2FQSyWo)
> 
> This is not enough It needs Visual Studio Community plus the "workload" Desktop C++
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311177601-836b10be-b5b3-48df-913c-d09dcb16a0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExNzc2MDEtODM2YjEwYmUtYjViMy00OGRmLTkxM2MtZDA5ZGNiMTZhMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OWI1M2U4OWM1ZjRiYzk5N2Y5YTI0MWNhNzkzNmMwNGVhZGUyYWYxNjYwOTE4NzRiYjllNDdhM2I4MWUzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o1QXbM3SCeFL4V3SlBTnRJphF7k_HaXI9aLi0NHpoFU)
> 
> Now it builds
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311177062-378d2e49-5253-4ea9-962d-06bd9048c76c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExNzcwNjItMzc4ZDJlNDktNTI1My00ZWE5LTk2MmQtMDZiZDkwNDhjNzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3M2JjODc3YjBiOWEwZDIwMDdkYTBjMGQ2Yjk4OWVkNmVhNDk0MWE3MjI4MzJhMTZkODUyYTYxOWYyMjk3MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fJNuwV-oFfqIX6V4K28y8braxCWh5jPphyQgwPvBDLQ)
> 
> TripoSR-main>pip install -r requirements.txt gets pasts torchmcubes !
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311178440-ab4bc9b0-dd22-4775-b276-8c380aec8fd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExNzg0NDAtYWI0YmM5YjAtZGQyMi00Nzc1LWIyNzYtOGMzODBhZWM4ZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMzlhNmI0MzVmZDZjNWU2YjMxM2VhN2NiZjIyYzc4ZTg3OGQ4MTM5ZTBjZmRmMTAzMjU1YTllZDg3Y2UwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o5aHozPvDiFHr8B2tudKC8U0MxxJn82Wa8C7-vMOOIE)
> 
> installed rust package manager https://win.rustup.rs/x86_64
> 
> and requirements finishes
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311179637-995dfa96-b08c-4242-9141-fb7b5d5d0fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExNzk2MzctOTk1ZGZhOTYtYjA4Yy00MjQyLTkxNDEtZmI3YjVkNWQwZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MjY1MTNkYmZhNjgzZTJiZjkzYjlmODI2MDQ4ZjIyZTdiOWRkNzdmZjBmNjk1ODY4Yzk5ZmVhNDE3YTk3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yDFzZbkKtUmVODw9A3xOhHhaKek_qiQ-kuh7C9M9WsY)
> 
> total success
> 
> ![image](https://private-user-images.githubusercontent.com/10621885/311180572-2d2508f6-6cf5-4177-876c-75da223bd325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2NjQsIm5iZiI6MTcxMDc0NjM2NCwicGF0aCI6Ii8xMDYyMTg4NS8zMTExODA1NzItMmQyNTA4ZjYtNmNmNS00MTc3LTg3NmMtNzVkYTIyM2JkMzI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3M2U3ZTE4YTdlZDE4MDkzMjNlOWRjMTZjNzA5OGFiMDYyZWM0ZDgxZjQzYzgzMGViMzIwMWIwYWFlZWZkMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_nlmjVMwUeAFLhx5SbNsA617ad5D7mk04sqW7H94uk)
> 
> So recap, for anyone ending up here from TripoSR
> 
> here are your steps for a fresh windows 10 install
> 
> ```
> install python https://www.python.org/ftp/python/3.12.2/python-3.12.2-amd64.exe
> install MS Visual C++ at https://visualstudio.microsoft.com/visual-cpp-build-tools/
> choose Visual Studio community  and Desktop C++ and build tools
> Install rust package manager from https://win.rustup.rs/x86_64
> download TripoSR https://github.com/VAST-AI-Research/TripoSR/archive/refs/heads/main.zip
> uncompress tar -xf TripoSR-main.zip
> restart your terminal and maybe reboot here
> install torch with   pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> run the following
> pip install --upgrade setuptools
> pip install wheel
> pip install ninja
> pip install -r requirements.txt
> ```
> 
> and then magic !
> 
> python run.py examples/chair.png --output-dir output/
> 
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools":

thx my friend,"install wheel" solved my problem ,too. :)
