### ISSUE TITLE
Can't find python module

### ISSUE THREAD

**Issue by RickyYXY** [tatsy/mcubes_pytorch#6]
Thanks for this package, but after I installed it by _pip install git+https://github.com/tatsy/torchmcubes.git_, I still got **ModuleNotFoundError: No module named 'torchmcubes'**, why is that???

**Comment by tatsy** [comment]
Hi @RickyYXY,

It seems strange, but it's possible that my preparation for Pip is inappropriate. Can you show me your environment, i.e., OS, graphics card, Python, PyTorch, CUDA, CUDNN versions, please?

**Comment by RickyYXY** [comment]
Thanks for your reply!
My machine's environment is:
OS: Linux Ubuntu
Graphic Card: Nvidia Titan RTX
CUDA Ver: 10.2
CuDDN: 7605
Pytorch: 1.8.0
Python: 3.8

It is strange that my pip printed out that I have successfully installed the lib, but when I import it in the same python environment, it says can't find out the lib

**Comment by tatsy** [comment]
Are you sure that you use the same environment for Python and pip? I wonder if both of them are of the system or Anaconda?

It would be helpful if you share the result of "which python" and "which pip".

**Comment by myavartanoo** [comment]
Same issue

**Comment by trancelestial** [comment]
Same issue here

**Comment by tatsy** [comment]
Hey guys, I have already understood there's something wrong, but just saying "same issue" does not help anybody, right?

Can you elaborate the problem with your environment, what you did, and what you got from the console. As far as I tested on my environment, pip installation works properly.

**Comment by tatsy** [comment]
I've updated `setup.py` and a bit more. I think the problem should be fixed now.
