### ISSUE TITLE
backward support?

### ISSUE THREAD

**Issue by alibool** [tatsy/mcubes_pytorch#9]
Thanks for this great package. Does the function implemented here support backward?

**Comment by tatsy** [comment]
No, and probably will not.
Differentiating marching cubes is not really straightforward. See the paper below.
https://openaccess.thecvf.com/content_cvpr_2018/papers/Liao_Deep_Marching_Cubes_CVPR_2018_paper.pdf

**Comment by HaFred** [comment]
Hey it seems available now, and it looks ok just by glancing:
https://github.com/SarahWeiii/diso/tree/main

**Comment by HaFred** [comment]
And from the Table 1 of _Flexible Isosurface Extraction for Gradient-Based Mesh Optimization_, it can be found that MC should really support a backward.
